apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-service-config
  labels:
    app: wallet-service
    component: backend
    version: v1
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/wallet_db"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
