apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
    component: backend
spec:
  type: ClusterIP
  selector:
    app: wallet-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
